import os

from dotenv import load_dotenv

load_dotenv()

REDDIT_USERNAME = os.getenv('REDDIT_USERNAME')
REDDIT_PASSWORD = os.getenv('REDDIT_PASSWORD')
REDDIT_USER_AGENT = os.getenv('REDDIT_USER_AGENT')
REDDIT_CLIENT_ID = os.getenv('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = os.getenv('REDDIT_CLIENT_SECRET')
REDDIT_SUBREDDIT = os.getenv('REDDIT_SUBREDDIT')
SLEEP_DURATION = os.getenv('SLEEP_DURATION')
ASSISTANT_MODE_ID = os.getenv('ASSISTANT_MODE_ID')
